### ISSUE TITLE
Improve the way the default CDR version is configured in the R and Python setup snippets.

### ISSUE THREAD

**Issue by deflaux** [all-of-us/workbench-snippets#2]
Per this discussion https://github.com/all-of-us/code-snippets/pull/1#discussion_r278576079 with @kelseyMayo.

**Comment by calbach** [comment]
This is burning me in testing so I feel compelled to fix it. @deflaux is this a palatable short-term solution?

Python:

```
# Get the BigQuery curated dataset for the current workspace context.
with open('.all_of_us_config.json') as f:  
  config = json.load(f)
  DATASET = config['CDR_VERSION_CLOUD_PROJECT'] + '.' + config['CDR_VERSION_BIGQUERY_DATASET']
```

R:

```
# Get the BigQuery curated dataset for the current workspace context.
DATASET <- system("echo $(jq -r '.CDR_VERSION_CLOUD_PROJECT' .all_of_us_config.json).$(jq -r '.CDR_VERSION_BIGQUERY_DATASET' .all_of_us_config.json)", intern = TRUE)
```

**Comment by calbach** [comment]
Note: this only works if you're running in the "right" directory on the VM (`/workspaces/<ws-name>/*`), not subdirectories

**Comment by calbach** [comment]
We will also still aim to get to an environment variable, but it may take time as it's blocked on other work.

**Comment by deflaux** [comment]
Yes, looks good to me for now.  Be sure to use `DATASET` as the name of the constant in the R snippet.

**Comment by calbach** [comment]
Thanks, good catch (updated in my snippet too)
